"""
Public surface of the queue abstraction. Callers import from here and stay
unaware of which backend is active.

Mirrors `apps/api/src/queue/index.ts`.
"""

from .aws_sqs_port import AwsSqsPort
from .factory import (
    DEFAULT_AWS_REGION,
    DEFAULT_QUEUE_BACKEND,
    DEFAULT_REDIS_URL,
    QUEUE_BACKENDS,
    Env,
    QueueClientDeps,
    QueueConfig,
    RedisQueueConfig,
    SqsQueueConfig,
    create_queue_client,
    create_queue_client_from_config,
    resolve_queue_config,
)
from .publish_job import (
    CONTENT_MAX_LENGTH,
    CONTENT_MIN_LENGTH,
    ENQUEUED_AT_PATTERN,
    FIELD_ORDER,
    JOB_ID_PATTERN,
    PLATFORM_ALLOW_LIST,
    POST_ID_PATTERN,
    JobDescription,
    ParseResult,
    character_length,
    create_publish_job,
    describe_job,
    format_enqueued_at,
    is_platform,
    parse_publish_job,
    serialize_publish_job,
    validate_publish_job,
)
from .redis_queue_client import (
    DEFAULT_REDIS_QUEUE_KEYS,
    DEFAULT_VISIBILITY_TIMEOUT_SECONDS,
    ReapResult,
    RedisCommands,
    RedisQueueClient,
    RedisQueueKeys,
)
from .sqs_queue_client import SQS_MAX_WAIT_SECONDS, SqsMessage, SqsPort, SqsQueueClient
from .types import (
    SCHEMA_VERSION,
    DeadLetterEvent,
    DeadLetterListener,
    DeadLetterReason,
    JobHandle,
    Platform,
    PublishJob,
    QueueBackend,
    QueueClient,
    QueueConfigError,
    ReceivedJob,
    RedisJobHandle,
    SqsJobHandle,
)

__all__ = [
    "AwsSqsPort",
    "CONTENT_MAX_LENGTH",
    "CONTENT_MIN_LENGTH",
    "DEFAULT_AWS_REGION",
    "DEFAULT_QUEUE_BACKEND",
    "DEFAULT_REDIS_QUEUE_KEYS",
    "DEFAULT_REDIS_URL",
    "DEFAULT_VISIBILITY_TIMEOUT_SECONDS",
    "ENQUEUED_AT_PATTERN",
    "Env",
    "FIELD_ORDER",
    "JOB_ID_PATTERN",
    "JobDescription",
    "JobHandle",
    "PLATFORM_ALLOW_LIST",
    "POST_ID_PATTERN",
    "ParseResult",
    "Platform",
    "PublishJob",
    "QUEUE_BACKENDS",
    "QueueBackend",
    "QueueClient",
    "QueueClientDeps",
    "QueueConfig",
    "QueueConfigError",
    "ReapResult",
    "ReceivedJob",
    "RedisCommands",
    "RedisJobHandle",
    "RedisQueueClient",
    "RedisQueueConfig",
    "RedisQueueKeys",
    "SCHEMA_VERSION",
    "SQS_MAX_WAIT_SECONDS",
    "SqsJobHandle",
    "SqsMessage",
    "SqsPort",
    "SqsQueueClient",
    "SqsQueueConfig",
    "DeadLetterEvent",
    "DeadLetterListener",
    "DeadLetterReason",
    "character_length",
    "create_publish_job",
    "create_queue_client",
    "create_queue_client_from_config",
    "describe_job",
    "format_enqueued_at",
    "is_platform",
    "parse_publish_job",
    "resolve_queue_config",
    "serialize_publish_job",
    "validate_publish_job",
]
