"""
Public surface of the worker's observability module.

Mirrors `apps/api/src/observability/index.ts`, including its one deliberate
omission: `bootstrap.py` is absent, because importing it initializes `ddtrace`. It
is imported by exactly one file, the process entrypoint. Everything exported here is
safe to import from a test — no APM library, no socket, no Datadog account.
"""

from .metrics import (
    COUNTER,
    DEFAULT_DEPTH_INTERVAL_SECONDS,
    DEFAULT_DOGSTATSD_HOST,
    DEFAULT_DOGSTATSD_PORT,
    GAUGE,
    HISTOGRAM,
    INERT_SINK,
    JOBS_DURATION,
    JOBS_FAILED,
    JOBS_PROCESSED,
    NO_PLATFORM,
    QUEUE_DEPTH,
    WORKER_METRICS,
    DatagramSender,
    DogStatsdSink,
    JobDisposition,
    MetricsSink,
    QueueDepthSampler,
    UdpDatagramSender,
    WorkerMetrics,
    create_dogstatsd_sink,
    format_datagram,
    render_value,
    sanitize_tag,
)
from .observability import (
    INERT_OBSERVABILITY,
    WorkerObservability,
    create_observability,
)
from .tracing import (
    DEFAULT_ENV,
    DEFAULT_SERVICE,
    INERT_TRACING,
    JOB_SPAN_NAME,
    NO_SPAN,
    DatadogTracing,
    InertTracing,
    JobSpan,
    SpanPort,
    TracerLoader,
    TracerPort,
    Tracing,
    TracingOptions,
    create_tracing,
    tracing_options_from_env,
)

__all__ = [
    "COUNTER",
    "DEFAULT_DEPTH_INTERVAL_SECONDS",
    "DEFAULT_DOGSTATSD_HOST",
    "DEFAULT_DOGSTATSD_PORT",
    "DEFAULT_ENV",
    "DEFAULT_SERVICE",
    "GAUGE",
    "HISTOGRAM",
    "INERT_OBSERVABILITY",
    "INERT_SINK",
    "INERT_TRACING",
    "JOBS_DURATION",
    "JOBS_FAILED",
    "JOBS_PROCESSED",
    "JOB_SPAN_NAME",
    "NO_PLATFORM",
    "NO_SPAN",
    "QUEUE_DEPTH",
    "WORKER_METRICS",
    "DatadogTracing",
    "DatagramSender",
    "DogStatsdSink",
    "InertTracing",
    "JobDisposition",
    "JobSpan",
    "MetricsSink",
    "QueueDepthSampler",
    "SpanPort",
    "TracerLoader",
    "TracerPort",
    "Tracing",
    "TracingOptions",
    "UdpDatagramSender",
    "WorkerMetrics",
    "WorkerObservability",
    "create_dogstatsd_sink",
    "create_observability",
    "create_tracing",
    "format_datagram",
    "render_value",
    "sanitize_tag",
    "tracing_options_from_env",
]
